# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      $PATH = pwd
      cd DCC32
      pwd
      .\DCC32.EXE -Q -B $path\CardPanel.dpr
      pwd
      cd ..
      pwd
      ls
    
      


