# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  CardPanel

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      $PATH = pwd
      ls
      cd DCC32
      .\DCC32.EXE -Q -B $path\CardPanel.dpr
      cd ..
      TCrdPanel.py
    
      


